// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package ee.itcollege.example.entities;

import ee.itcollege.example.entities.Regiment;
import java.lang.Long;

privileged aspect Regiment_Roo_Entity {
    
    public static Regiment Regiment.findRegiment(Long id) {
        if (id == null) return null;
        return entityManager().find(Regiment.class, id);
    }
    
}
